export const ADD_ITEM_TO_CHECKOUT = 'ADD_ITEM_TO_CHECKOUT';
export const REMOVE_ITEM_FROM_CHECKOUT = 'REMOVE_ITEM_FROM_CHECKOUT';

export const STDINOUT_IN = 'STDINOUT_IN';
export const STDINOUT_OUT = 'STDINOUT_OUT';
export const STDINOUT_CLEAR = 'STDINOUT_CLEAR';
export const STDINOUT_BACKSPACE = 'STDINOUT_BACKSPACE';

export const APPOINTMENT_PICK_DATE = 'APPOINTMENT_PICK_DATE';
